on:
  repository_dispatch:
    types: [run-playwright-tests]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Add your test steps here
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Playwright tests
        run: npx playwright test